import { Metadata } from "next";
import Link from "next/link";
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardHeader, 
  CardTitle 
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms and Conditions | YouTube Summarizer",
  description: "Terms and conditions for using the YouTube Summarizer service. Learn about our policies, user responsibilities, and legal information.",
};

export default function TermsAndConditionsPage() {
  return (
    <main className="min-h-screen py-12 px-4 sm:px-6 lg:px-8 bg-gray-50">
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center mb-8">
          <Button
            variant="ghost"
            size="icon"
            className="mr-4"
            asChild
          >
            <Link href="/">
              <ArrowLeft className="h-5 w-5" />
            </Link>
          </Button>
          <h1 className="text-2xl font-bold">Terms and Conditions</h1>
        </div>
        
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>YouTube Summarizer Terms of Service</CardTitle>
            <CardDescription>
              Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
            </CardDescription>
          </CardHeader>
          <CardContent className="prose prose-gray max-w-none">
            <p>
              Welcome to YouTube Summarizer. Please read these terms of service ("Terms") carefully as they contain important information about your legal rights, remedies, and obligations. By accessing or using YouTube Summarizer, you agree to comply with and be bound by these Terms.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using our service, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use our service.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3">2. Description of Service</h2>
            <p>
              YouTube Summarizer provides an AI-powered tool that generates text summaries of YouTube videos. The service may include features such as video analysis, transcript generation, and summary creation. We reserve the right to modify, suspend, or discontinue the service at any time without notice.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3">3. User Accounts</h2>
            <p>
              To access certain features of the service, you may need to create an account. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3">4. User Conduct</h2>
            <p>
              You agree not to use the service to:
            </p>
            <ul className="list-disc ml-6 my-3">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on the rights of others</li>
              <li>Attempt to gain unauthorized access to the service or computer systems</li>
              <li>Engage in any activity that interferes with or disrupts the service</li>
              <li>Harvest or collect user data without consent</li>
              <li>Use the service for any illegal or unauthorized purpose</li>
            </ul>
            
            <h2 className="text-xl font-semibold mt-6 mb-3">5. Intellectual Property</h2>
            <p>
              The service and its original content, features, and functionality are owned by YouTube Summarizer and are protected by copyright, trademark, and other intellectual property laws. The summaries generated by our service are provided for your personal use only.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3">6. Payment and Subscription</h2>
            <p>
              Some aspects of the service may be offered on a subscription basis. By choosing a subscription plan, you agree to pay the fees associated with your selected plan. You can find more information about our refund policy on our <Link href="/refund-and-cancellation" className="text-blue-600 hover:underline">Refund and Cancellation</Link> page.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, YouTube Summarizer shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3">8. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will provide notice of any material changes through the service or by other means. Your continued use of the service after such modifications constitutes your acceptance of the updated Terms.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3">9. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please <Link href="/contact-us" className="text-blue-600 hover:underline">contact us</Link>.
            </p>
          </CardContent>
        </Card>
      </div>
    </main>
  );
} 